name: Secret Scan
on:
  pull_request: { branches: ['*'] }
  push: { branches: ['dev', 'main'] }
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2.3.0
        with:
          args: detect --source . --no-banner -v --redact --report-format sarif --report-path gitleaks.sarif
      - name: Upload Gitleaks SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
